### ISSUE TITLE
UnknownOperationException in Reasoner

### ISSUE THREAD

**Issue by eichelbe** [SSEHUB/EASyProducer#38]
While runtime reasoning (monitoring) over the QM model - sorry no further details available:

de.uni_hildesheim.sse.model.cst.UnknownOperationException: unknown operation of signature size(setOf(NonEmptyString), setOf(NonEmptyString))
    at de.uni_hildesheim.sse.model.cst.OCLFeatureCall.customInferDatatype(OCLFeatureCall.java:319)
    at de.uni_hildesheim.sse.model.cst.OCLFeatureCall.dfltInferDatatype(OCLFeatureCall.java:183)
    at de.uni_hildesheim.sse.model.cst.OCLFeatureCall.inferDatatype(OCLFeatureCall.java:107)
    at de.uni_hildesheim.sse.reasoning.reasoner.model.CopyVisitor.visitOclFeatureCall(CopyVisitor.java:133)
    at de.uni_hildesheim.sse.model.cst.OCLFeatureCall.accept(OCLFeatureCall.java:398)
    at de.uni_hildesheim.sse.reasoning.reasoner.model.CopyVisitor.visitOclFeatureCall(CopyVisitor.java:124)
    at de.uni_hildesheim.sse.model.cst.OCLFeatureCall.accept(OCLFeatureCall.java:398)
    at de.uni_hildesheim.sse.reasoning.reasoner.Resolver.copyVisitor(Resolver.java:1011)
    at de.uni_hildesheim.sse.reasoning.reasoner.Resolver.transformConstraints(Resolver.java:985)
    at de.uni_hildesheim.sse.reasoning.reasoner.Resolver.processConstraints(Resolver.java:616)
    at de.uni_hildesheim.sse.reasoning.reasoner.Resolver.resolve(Resolver.java:217)
    at de.uni_hildesheim.sse.reasoning.reasoner.Engine.reason(Engine.java:79)
    at de.uni_hildesheim.sse.reasoning.reasoner.Reasoner.check(Reasoner.java:43)
    at de.uni_hildesheim.sse.reasoning.core.frontend.ReasonerFrontend.check(ReasonerFrontend.java:325)
    at eu.qualimaster.monitoring.ReasoningTask.reason(ReasoningTask.java:166)
    at eu.qualimaster.monitoring.ReasoningTask.run(ReasoningTask.java:144)
    at java.util.TimerThread.mainLoop(Unknown Source)
    at java.util.TimerThread.run(Unknown Source)

**Comment by eichelbe** [comment]
Seems to occur due to uncontrolled parallel execution...
