### ISSUE TITLE
Installing experimental/deprecated bundle causes a LinkageError

### ISSUE THREAD

**Issue by eichelbe** [SSEHUB/EASyProducer#79]
Can be resolved by removing the optional experimental bundle.

Exception Trace: 
java.lang.LinkageError: loader constraint violation: when resolving method "net.ssehub.easy.varModel.confModel.Configuration.getProject()Lnet/ssehub/easy/varModel/model/Project;" the class loader (instance of org/eclipse/osgi/internal/loader/EquinoxClassLoader) of the current class, net/ssehub/easy/reasoning/core/frontend/ReasonerFrontend$1, and the class loader (instance of org/eclipse/osgi/internal/loader/EquinoxClassLoader) for the method's defining class, net/ssehub/easy/varModel/confModel/Configuration, have different Class objects for the type net/ssehub/easy/varModel/model/Project used in the signature

                at net.ssehub.easy.reasoning.core.frontend.ReasonerFrontend$1.initializeConfiguration(ReasonerFrontend.java:80)

                at net.ssehub.easy.varModel.confModel.Configuration.init(Configuration.java:269)

                at net.ssehub.easy.varModel.confModel.Configuration.<init>(Configuration.java:193)

                at net.ssehub.easy.varModel.confModel.Configuration.<init>(Configuration.java:121)

                at net.ssehub.easy.producer.core.varMod.container.ProjectContainer.<init>(ProjectContainer.java:44)

                at net.ssehub.easy.producer.core.varMod.container.ProjectContainer.<init>(ProjectContainer.java:28)

                at net.ssehub.easy.producer.core.persistence.datatypes.PersistentProject.<init>(PersistentProject.java:70)

                at net.ssehub.easy.producer.core.persistence.standard.Persistencer.createProject(Persistencer.java:182)

                at net.ssehub.easy.producer.eclipse.persistency.eclipse.EclipsePersistencer.createProject(EclipsePersistencer.java:239)

                at net.ssehub.easy.producer.eclipse.persistency.eclipse.EclipsePersistencer.createEASyEclipseProject(EclipsePersistencer.java:118)

                at net.ssehub.easy.producer.eclipse.persistency.eclipse.EclipsePersistencer.createEASyProject(EclipsePersistencer.java:151)

                at net.ssehub.easy.producer.eclipse.persistency.project_creation.AbstractProjectCreator.createNewEASyProject(AbstractProjectCreator.java:166)

                at net.ssehub.easy.producer.eclipse.persistency.project_creation.AbstractProjectCreator.createProject(AbstractProjectCreator.java:104)

                at net.ssehub.easy.producer.eclipse.persistency.project_creation.NewProjectCreator.createEASyProject(NewProjectCreator.java:46)

                at net.ssehub.easy.producer.eclipse.persistency.project_creation.EASyProjectCreatorFactory.createNewProject(EASyProjectCreatorFactory.java:105)

                at net.ssehub.easy.producer.eclipse.persistency.project_creation.ProjectCreator.newPLP(ProjectCreator.java:112)

                at net.ssehub.easy.producer.ui.internal.NewEASyProjectWizard.performFinish(NewEASyProjectWizard.java:52)

                at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:790)

                at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:423)

                at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:618)

                at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)

                at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)

                at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)

                at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)

                at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4236)

                at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3824)

                at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)

                at org.eclipse.jface.window.Window.open(Window.java:794)

                at org.eclipse.ui.actions.NewProjectAction.run(NewProjectAction.java:115)

                at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)

                at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)

                at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)

                at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)

                at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)

                at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)

                at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4236)

                at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3824)

                at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)

                at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)

                at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)

                at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)

                at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)

                at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)

                at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)

                at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)

                at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)

                at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)

                at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)

                at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)

                at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)

                at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)

                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

                at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

                at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

                at java.lang.reflect.Method.invoke(Unknown Source)

                at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)

                at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)

                at org.eclipse.equinox.launcher.Main.run(Main.java:1519)

**Comment by eichelbe** [comment]
Just an idea... might happen if nightly and release are installed into the same Eclipse...

**Comment by eichelbe** [comment]
Happend only once, was an installation problem.
